# trains:
RED_LINE_ASHMONT = 'Red-Ashmont'
RED_LINE_BRAINTREE = 'Red-Braintree'
GREEN_LINE = 'Green'
GREEN_LINE_B = 'Green-B'
GREEN_LINE_C = 'Green-C'
GREEN_LINE_D = 'Green-D'
GREEN_LINE_E = 'Green-E'
BLUE_LINE = 'Blue'
ORANGE_LINE = 'Orange'

# status:
STATUS_AT_STATION = 'AT_STATION'
STATUS_IN_TRANSIT = 'IN_TRANSIT'
STATUS_UNKNOWN = 'UNKNOWN'