version: '2'
volumes:
  mysql:
services:
  db:
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "5310:3306"
    environment:
      MYSQL_USER: mbtapuller
      MYSQL_PASSWORD: mbtapuller
      MYSQL_ROOT_PASSWORD: mbtapuller
      MYSQL_DATABASE: mbtapuller
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
  mbtapuller-display:
    build:
      context: .
      dockerfile: Dockerfile-display
    volumes:
      - .:/app
    ports:
      - "5309:80"
    environment:
      - USE_MYSQL=1
    links:
      - db
  mbtapuller-pull:
    build:
      context: .
      dockerfile: Dockerfile-pull
    volumes:
      - .:/app
    environment:
      - USE_MYSQL=1
    links:
      - db